name: test_clean_architecture
description: "Test Clean Architecture"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  auto_route: ^9.2.2
  get: ^4.7.2
  carousel_slider_plus: ^7.0.2
  collection: ^1.18.0
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  custom_thumbnail_video: ^0.6.3
  dartz: ^0.10.1
  device_info_plus: ^11.1.1
  dio: ^5.5.0+1
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  equatable: ^2.0.5
  faker: ^2.1.0
  file_picker: ^8.0.6
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  firebase_remote_config: ^5.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_easy_dialogs: ^4.0.1
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^8.0.2
  html: ^0.15.4
  http_mock_adapter: ^0.6.1
  hydrated_bloc: ^9.1.5
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mention_tag_text_field: ^0.0.6
  outline_gradient_button: ^2.0.1+1
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  phosphor_flutter: ^2.1.0
  screenshot: ^3.0.0
  simple_animations: ^5.0.2
  simple_gradient_text: ^1.3.0
  sliver_tools: ^0.2.12
  syncfusion_flutter_charts: ^27.2.3
  textfield_tags: ^3.0.1
  webview_flutter: ^4.8.0
  smooth_page_indicator: ^1.2.1
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.3

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mockito: ^5.4.4
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - assets/images/
  #   - assets/images/profile/
  #   - assets/images/pengiriman/
  #   - assets/icons/
  #   - assets/images/category/
  #   - assets/images/transactions/
  #   - assets/fonts/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/poppins/Poppins-Thin.ttf
  #         weight: 100
  #       - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
  #         weight: 200
  #       - asset: assets/fonts/poppins/Poppins-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/poppins/Poppins-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/poppins/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/poppins/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
  #         weight: 800
  #       - asset: assets/fonts/poppins/Poppins-Black.ttf
  #         weight: 900
